name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add deadsnakes PPA
        run: sudo add-apt-repository ppa:deadsnakes/ppa -y

      - name: Update package list
        run: sudo apt-get update

      - name: Install python3.9-venv
        run: sudo apt-get install python3.9-venv -y

      - name: Set up virtual environment
        run: |
          if [ ! -d "venv" ]; then
            python3.9 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install python-telegram-bot[rate-limiter]
          else
            source venv/bin/activate
          fi

      - name: List installed Python packages
        run: |
          source venv/bin/activate
          pip list

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Deploy code to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-51-249-37.eu-north-1.compute.amazonaws.com '
          if [ ! -d "/usr/src/Python-3.9.0/Codeforces_bot/venv" ]; then
            cd /usr/src/Python-3.9.0/Codeforces_bot
            python3.9 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install python-telegram-bot[rate-limiter]
          else
            cd /usr/src/Python-3.9.0/Codeforces_bot
            source venv/bin/activate
          fi
          git pull
          sudo systemctl restart codeforces_bot'
