name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add deadsnakes PPA
        run: sudo add-apt-repository ppa:deadsnakes/ppa -y

      - name: Update package list
        run: sudo apt-get update

      - name: Install python3.9-venv
        run: sudo apt-get install python3.9-venv -y

      - name: Create virtual environment
        run: python3.9 -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Deploy code to EC2 instance
        run: |
          echo "$ssh-private-key" > kh.pem
          ssh -i kh.pem ubuntu@ec2-13-51-249-37.eu-north-1.compute.amazonaws.com 'cd /usr/src/Python-3.9.0/Codeforces_bot && git pull && sudo systemctl restart codeforces_bot'